export const perfumes = [
  {
    id: 1,
    name: "Chanel No. 5",
    brand: "Chanel",
    image: "https://example.com/chanel-no-5.jpg",
    price: 250,
    fragranceLevel: 4,
    inStock: true,
    description:
      "A timeless classic with a floral and aldehydic scent profile.",
    gender: "female",
  },
  {
    id: 2,
    name: "Dior Sauvage",
    brand: "Dior",
    image: "https://example.com/dior-sauvage.jpg",
    price: 200,
    fragranceLevel: 3,
    inStock: true,
    description: "A fresh and spicy fragrance inspired by the wild outdoors.",
    gender: "male",
  },
  {
    id: 3,
    name: "Creed Aventus",
    brand: "Creed",
    image: "https://example.com/creed-aventus.jpg",
    price: 450,
    fragranceLevel: 4,
    inStock: true,
    description: "A bold and sophisticated scent with fruity and woody notes.",
    gender: "male",
  },
  {
    id: 4,
    name: "Tom Ford Black Orchid",
    brand: "Tom Ford",
    image: "https://example.com/tom-ford-black-orchid.jpg",
    price: 300,
    fragranceLevel: 4,
    inStock: true,
    description: "A luxurious and sensual fragrance with rich, dark accords.",
    gender: "female",
  },
  {
    id: 5,
    name: "Gucci Bloom",
    brand: "Gucci",
    image: "https://example.com/gucci-bloom.jpg",
    price: 180,
    fragranceLevel: 2,
    inStock: true,
    description: "A light and airy floral fragrance perfect for daily wear.",
    gender: "female",
  },
  {
    id: 6,
    name: "Yves Saint Laurent Libre",
    brand: "YSL",
    image: "https://example.com/ysl-libre.jpg",
    price: 220,
    fragranceLevel: 3,
    inStock: true,
    description:
      "A bold and floral fragrance with a touch of lavender and orange blossom.",
    gender: "female",
  },
  {
    id: 7,
    name: "Versace Eros",
    brand: "Versace",
    image: "https://example.com/versace-eros.jpg",
    price: 120,
    fragranceLevel: 3,
    inStock: true,
    description: "A fresh and vibrant scent inspired by Greek mythology.",
    gender: "male",
  },
  {
    id: 8,
    name: "Paco Rabanne 1 Million",
    brand: "Paco Rabanne",
    image: "https://example.com/paco-rabanne-1-million.jpg",
    price: 150,
    fragranceLevel: 3,
    inStock: true,
    description: "A spicy and warm fragrance with a luxurious vibe.",
    gender: "male",
  },
  {
    id: 9,
    name: "Armani Code",
    brand: "Giorgio Armani",
    image: "https://example.com/armani-code.jpg",
    price: 190,
    fragranceLevel: 3,
    inStock: true,
    description: "A seductive and spicy fragrance perfect for evening wear.",
    gender: "male",
  },
  {
    id: 10,
    name: "Lancome La Vie Est Belle",
    brand: "Lancome",
    image: "https://example.com/lancome-la-vie-est-belle.jpg",
    price: 210,
    fragranceLevel: 4,
    inStock: true,
    description: "A sweet and floral fragrance celebrating the beauty of life.",
    gender: "female",
  },
  {
    id: 11,
    name: "Dolce & Gabbana Light Blue",
    brand: "Dolce & Gabbana",
    image: "https://example.com/dg-light-blue.jpg",
    price: 150,
    fragranceLevel: 2,
    inStock: true,
    description: "A fresh and citrusy fragrance perfect for summer days.",
    gender: "female",
  },
  {
    id: 12,
    name: "Victor & Rolf Flowerbomb",
    brand: "Victor & Rolf",
    image: "https://example.com/victor-rolf-flowerbomb.jpg",
    price: 260,
    fragranceLevel: 4,
    inStock: true,
    description: "A floral explosion of fragrance that captivates the senses.",
    gender: "female",
  },
  {
    id: 13,
    name: "Calvin Klein Euphoria",
    brand: "Calvin Klein",
    image: "https://example.com/ck-euphoria.jpg",
    price: 130,
    fragranceLevel: 2,
    inStock: true,
    description: "A mysterious and exotic scent with floral and fruity notes.",
    gender: "female",
  },
  {
    id: 14,
    name: "Hermès Terre d'Hermès",
    brand: "Hermès",
    image: "https://example.com/hermes-terre.jpg",
    price: 240,
    fragranceLevel: 3,
    inStock: true,
    description:
      "A sophisticated and earthy fragrance with citrus and wood notes.",
    gender: "male",
  },
  {
    id: 15,
    name: "Montblanc Explorer",
    brand: "Montblanc",
    image: "https://example.com/montblanc-explorer.jpg",
    price: 170,
    fragranceLevel: 2,
    inStock: true,
    description: "A woody and aromatic fragrance inspired by adventure.",
    gender: "male",
  },
  {
    id: 16,
    name: "Burberry Her",
    brand: "Burberry",
    image: "https://example.com/burberry-her.jpg",
    price: 140,
    fragranceLevel: 2,
    inStock: true,
    description:
      "A fruity and floral fragrance that captures the essence of London.",
    gender: "female",
  },
  {
    id: 17,
    name: "Jo Malone English Pear & Freesia",
    brand: "Jo Malone",
    image: "https://example.com/jo-malone-english-pear.jpg",
    price: 170,
    fragranceLevel: 2,
    inStock: false,
    description: "A fresh and fruity scent with a subtle floral undertone.",
    gender: "female",
  },
  {
    id: 18,
    name: "Bvlgari Man in Black",
    brand: "Bvlgari",
    image: "https://example.com/bvlgari-man-in-black.jpg",
    price: 220,
    fragranceLevel: 3,
    inStock: false,
    description: "A bold and intense fragrance with spicy and leather notes.",
    gender: "male",
  },
  {
    id: 19,
    name: "Givenchy L'Interdit",
    brand: "Givenchy",
    image: "https://example.com/givenchy-linterdit.jpg",
    price: 180,
    fragranceLevel: 3,
    inStock: false,
    description: "A bold and modern scent with white floral and woody notes.",
    gender: "female",
  },
  {
    id: 20,
    name: "Maison Francis Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    image: "https://example.com/mfk-baccarat-rouge.jpg",
    price: 0,
    fragranceLevel: 4,
    inStock: false,
    description: "An exquisite blend of floral, amber, and woody notes.",
    gender: "female",
  },
];



export const reviews = [
  {
    productId: 1,
    reviews: [
      {
        name: "Alice Johnson",
        rating: 5,
        comment:
          "A timeless classic! The scent lasts all day and feels luxurious.",
      },
      {
        name: "Sophia Martinez",
        rating: 4,
        comment: "Very elegant, but a bit too strong for my preference.",
      },
    ],
  },
  {
    productId: 2,
    reviews: [
      {
        name: "Liam Smith",
        rating: 3,
        comment: "Fresh and clean, but it doesn't last long on me.",
      },
      {
        name: "Ethan Brown",
        rating: 5,
        comment:
          "Perfect for daily wear. The scent is refreshing and masculine.",
      },
    ],
  },
  {
    productId: 3,
    reviews: [
      {
        name: "Olivia Davis",
        rating: 4,
        comment: "Bold and sophisticated, but a bit pricey.",
      },
    ],
  },
  {
    productId: 17,
    reviews: [
      {
        name: "Emma Wilson",
        rating: 2,
        comment:
          "A bit too light for my liking, but the fruity notes are nice.",
      },
      {
        name: "Noah Anderson",
        rating: 1,
        comment: "Not what I expected, the scent disappears too quickly.",
      },
    ],
  },
  {
    productId: 18,
    reviews: [
      {
        name: "Ava Thomas",
        rating: 4,
        comment: "Strong and spicy, perfect for evening occasions.",
      },
      {
        name: "Mason Garcia",
        rating: 3,
        comment: "Good, but the leather notes are too intense for me.",
      },
    ],
  },
  {
    productId: 19,
    reviews: [
      {
        name: "Isabella Martinez",
        rating: 5,
        comment:
          "Absolutely stunning! A perfect blend of floral and woody notes.",
      },
    ],
  },
  {
    productId: 20,
    reviews: [
      {
        name: "Lucas Hernandez",
        rating: 5,
        comment: "Exquisite and luxurious. Worth every penny!",
      },
      {
        name: "Mia Clark",
        rating: 4,
        comment: "Beautiful scent, but the price is a bit too high.",
      },
    ],
  },
];
